<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PC" failures="2" tests="3" name="BankingApp Test(failed)(failed)" time="49.583" errors="0" timestamp="09 Aug 2023 08:42:30 GMT">
  <testcase classname="com.inetbanking.testCases.TCC_AddCustomer_003" name="addNewCustomer" time="15.642">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.inetbanking.testCases.TCC_AddCustomer_003.addNewCustomer(TCC_AddCustomer_003.java:52)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- addNewCustomer -->
  <testcase classname="com.inetbanking.testCases.TC_login_001" name="logintest" time="4.184"/>
  <testcase classname="com.inetbanking.testCases.TC_LoginDDT_002" name="loginDDT" time="0.838">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: loginDDT([])
Arguments: [(java.lang.String) mngr516206,(java.lang.String) jAsemej]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: loginDDT([])
Arguments: [(java.lang.String) mngr516206,(java.lang.String) jAsemej]
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- BankingApp Test(failed)(failed) -->
